version: '3.8'

services:

  db:
    image: postgres:15
    container_name: log_anomary_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: log_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
    container_name: log_anomary_app
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgressql://user:password@db:5432/log_db
    depends_on:
      - db

volumes:
  postgres_data:
